import * as validator from "validator";
import { Address } from "../src/Address";
import { default as Guards } from "../src/validation/Guards";

describe("Address", () => {
    it("id is autogenerated", () => {
        const address = new Address("street", "zipCode", "city", "country");
        expect(address.id).toBeDefined();
        expect(validator.isUUID(address.id)).toBe(true);
        expect(Guards.isIdentifiable(address)).toBe(true);
    });
    it("properties can only be set in the constructor", () => {
        // const address = new Address("street", "zipCode", "city", "country");
        // error TS2540: Cannot assign to 'city' because it is a constant or a read-only property.
        // address.city = "another city";
    });
});
